import React from "react";
import Link from "next/link";
import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import { Button, buttonVariants } from "@/components/ui/button";
import MaxWidthWrapper from "@/components/Elements/MaxWidthWrapper";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const DashboardLayout = ({
  children,
}: Readonly<{ children: React.ReactNode }>) => {
  return (
    <main>
      <MaxWidthWrapper>
        <nav>
          <Breadcrumb>
            <BreadcrumbList className="text-6xl my-20">
              <BreadcrumbItem>
                <BreadcrumbLink href="/landing">Your Bots</BreadcrumbLink>
              </BreadcrumbItem>
              <BreadcrumbSeparator />
              <BreadcrumbItem>
                <BreadcrumbPage>BotName</BreadcrumbPage>
              </BreadcrumbItem>
            </BreadcrumbList>
          </Breadcrumb>
        </nav>
        <div className="min-h-[40svh] grid grid-cols-12 gap-4">
          <div className="col-span-2 flex flex-col gap-6 bg-gray-200">
            <Link
              href={"/dashboard/overview"}
              className={cn(buttonVariants({ variant: "default" }))}
            >
              Overview
            </Link>
            <Link
              href={"/dashboard/settings"}
              className={cn(buttonVariants({ variant: "default" }))}
            >
              Settings
            </Link>
          </div>
          <div className="col-span-10">{children}</div>
        </div>
      </MaxWidthWrapper>
    </main>
  );
};

export default DashboardLayout;
